# Generated by Django 3.1.7 on 2021-03-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uniquelid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(default='', max_length=250, verbose_name='Phone Number')),
                ('site', models.TextField(verbose_name='Site')),
                ('state', models.TextField(verbose_name='Site')),
                ('join_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('sale_person', models.TextField(verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Unique LID',
                'verbose_name_plural': 'Unique LIDs',
            },
        ),
    ]
