# Generated by Django 3.1.7 on 2021-03-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquelid',
            name='sale_person',
            field=models.TextField(verbose_name='Sales person'),
        ),
        migrations.AlterField(
            model_name='uniquelid',
            name='state',
            field=models.TextField(verbose_name='State'),
        ),
    ]
