# Generated by Django 3.1.7 on 2021-03-26 10:28

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_auto_20210324_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrandProfitAbilityReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('created_for', models.DateField()),
                ('data', picklefield.fields.PickledObjectField(default=dict, editable=False)),
                ('type', models.IntegerField(default=0)),
                ('from_server', models.IntegerField(default=0)),
                ('from_id', models.IntegerField(default=0)),
            ],
        ),
    ]
